---

# RabbitMQ official install
- name: "add the official rabbitmq repository's key"
  apt_key: url=https://www.rabbitmq.com/rabbitmq-release-signing-key.asc
  when: not rabbitmq_os_package

- name: add the official rabbitmq repository
  copy:
    src=files/rabbitmq.list
    dest=/etc/apt/sources.list.d/
    backup=yes
  register: aptrepo
  when: not rabbitmq_os_package

- name: install rabbitmq-server
  apt: name=rabbitmq-server update_cache=yes
  register: rmq_install

- name: stop rabbitmq-server if just installed the package to ensure clustering
  service: name=rabbitmq-server state=stopped
  when: rmq_install.changed and rabbitmq_cluster

- name: enable rabbitmq-server to survive reboot
  service: name=rabbitmq-server enabled=yes
